import { useEffect, useState } from 'react';
import { api, json, upload } from './api';
import { JobProgress, UploadProgress, useTask } from './JobProgress';
import { SeparationProfile } from './SeparationProfile';
import type { Profile } from './SeparationProfile';

interface Artifact { id:string;name:string;role:string;exists:boolean;metadata:{kind?:string;purpose?:string;singer?:string;stem?:string;model_id?:string}; }
interface Engines {rvc:{ready:boolean};separation:{models:{id:string;name:string;ready:boolean}[]};}
const stemNames:Record<string,string>={instrumental:'伴奏',backing:'和声',lead:'主唱',vocals:'人声'};

export function ConversionPanel() {
  const [items,setItems]=useState<Artifact[]>([]),[engines,setEngines]=useState<Engines|null>(null);
  const [files,setFiles]=useState<File[]>([]),[singer,setSinger]=useState(''),[kind,setKind]=useState('song');
  const [audio,setAudio]=useState(''),[model,setModel]=useState(''),[index,setIndex]=useState('');
  const [pitch,setPitch]=useState(0),[indexRate,setIndexRate]=useState(.5),[protect,setProtect]=useState(.33),[rmsMix,setRmsMix]=useState(1);
  const [segment,setSegment]=useState(256),[overlap,setOverlap]=useState(4),[profile,setProfile]=useState<Profile>('balanced'),[vocalDb,setVocalDb]=useState(0),[instDb,setInstDb]=useState(0),[backingDb,setBackingDb]=useState(0),[includeBacking,setIncludeBacking]=useState(false),[format,setFormat]=useState('wav');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[uploadProgress,setUploadProgress]=useState<{done:number;total:number}|null>(null);
  const separationTask=useTask('conversion:separation'),convertTask=useTask('conversion:voice'),coverTask=useTask('conversion:cover');
  async function refresh(){const [a,e]=await Promise.all([api<{items:Artifact[]}>('/artifacts'),api<Engines>('/engines')]);setItems(a.items);setEngines(e);}
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
  async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const sources=items.filter(i=>i.exists&&i.role==='source'&&i.metadata.purpose==='conversion');
  const inputs=items.filter(i=>i.exists&&i.metadata.purpose==='conversion'&&(i.role==='source'||['vocals','lead','dry','clean'].includes(i.metadata.stem??'')));
  const selected=items.find(i=>i.id===audio), models=items.filter(i=>i.exists&&i.metadata.kind==='rvc_model'),indexes=items.filter(i=>i.exists&&i.metadata.kind==='rvc_index'&&i.metadata.model_id===model);
  const ready=(id:string)=>engines?.separation.models.some(m=>m.id===id&&m.ready);
  const parameters={model_id:model,index_id:index||null,pitch,index_rate:indexRate,protect,rms_mix:rmsMix};
  return <section><div className="section-head"><div><h2>转换素材与翻唱</h2><p>导入要转换的歌曲或干声，分离可下载的音轨，再选择目标音色。</p></div><button disabled={busy} onClick={()=>void action(refresh)}>刷新</button></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
    <article className="card"><h3>导入转换素材</h3><p>这里的音频仅用于转换与混音，和训练素材分别管理。</p><div className="toolbar"><label>原唱 / 素材歌手 <input aria-label="转换素材歌手" value={singer} onChange={e=>setSinger(e.target.value)}/></label><input aria-label="转换音源文件" type="file" multiple accept="audio/*,.flac,.m4a,.ogg" onChange={e=>setFiles(Array.from(e.target.files??[]))}/><select aria-label="转换素材类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="song">完整歌曲</option><option value="dry_vocal">干声 / 独立音轨</option></select><button className="primary" disabled={busy||!files.length||!singer.trim()} onClick={()=>void action(async()=>{try{for(const file of files){const form=new FormData();form.append('file',file);form.append('singer',singer);form.append('kind',kind);form.append('purpose','conversion');setUploadProgress({done:0,total:0});const result=await upload<{id:string}>('/sources',form,setUploadProgress);setAudio(result.id);}await refresh();setMessage('转换素材已导入，可一键分离伴奏和和声。');}finally{setUploadProgress(null);}})}>导入转换音源</button></div><UploadProgress value={uploadProgress}/></article>
    <article className="card"><h3>一键分离伴奏与和声</h3><SeparationProfile value={profile} onChange={value=>{setProfile(value);setOverlap(value==='quality'?8:value==='fast'?2:4);}}/><div className="toolbar"><label>转换输入 <select aria-label="转换输入音频" value={audio} onChange={e=>setAudio(e.target.value)}><option value="">选择转换歌曲或干声</option>{inputs.map(i=><option key={i.id} value={i.id}>{i.metadata.singer} / {i.name}</option>)}</select></label><label>分块长度 <input className="number" type="number" min="64" max="512" value={segment} onChange={e=>setSegment(Number(e.target.value))}/></label><label>重叠 <input className="number" type="number" min="2" max="50" value={overlap} onChange={e=>setOverlap(Number(e.target.value))}/></label><button className="primary" disabled={busy||separationTask.running||!sources.some(i=>i.id===audio)||!ready('lead_melband_aufr33')||(selected?.metadata.kind==='song'&&!ready('vocals_melband_unwa'))} onClick={()=>void action(async()=>{separationTask.track(await api<{id:string}>('/song-separation',json({source_id:audio,segment_size:segment,overlap,profile})));})}>一键分离伴奏和和声</button></div><p>歌曲先分离人声 / 伴奏，再分离主唱 / 和声；干声只分离主唱 / 和声。全部音轨可试听和下载。</p><JobProgress id={separationTask.id} onComplete={job=>void action(async()=>{await refresh();if(job.metadata.outputs?.lead)setAudio(job.metadata.outputs.lead);})}/></article>
    <article className="card"><h3>音色转换与自动翻唱</h3><div className="toolbar"><label>目标音色 <select aria-label="目标音色模型" value={model} onChange={e=>{setModel(e.target.value);setIndex(items.find(i=>i.metadata.kind==='rvc_index'&&i.metadata.model_id===e.target.value)?.id??'');}}><option value="">选择训练或导入的模型</option>{models.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>检索索引 <select aria-label="检索索引" value={index} onChange={e=>setIndex(e.target.value)}><option value="">不使用索引</option>{indexes.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div>
      <div className="toolbar"><label>变调 <input className="number" type="number" min="-24" max="24" value={pitch} onChange={e=>setPitch(Number(e.target.value))}/> 半音</label><label>索引比例 <input className="number" type="number" min="0" max="1" step=".05" value={indexRate} onChange={e=>setIndexRate(Number(e.target.value))}/></label><label>清辅音保护 <input className="number" type="number" min="0" max=".5" step=".01" value={protect} onChange={e=>setProtect(Number(e.target.value))}/></label><label>响度包络混合 <input className="number" type="number" min="0" max="1" step=".05" value={rmsMix} onChange={e=>setRmsMix(Number(e.target.value))}/></label></div>
      <button className="primary" disabled={busy||convertTask.running||!audio||!model||!engines?.rvc.ready||selected?.metadata.kind==='song'} onClick={()=>void action(async()=>{convertTask.track(await api<{id:string}>('/conversion',json({audio_id:audio,...parameters})));})}>转换干声</button>{selected?.metadata.kind==='song'&&<small>完整歌曲请先分离，或使用下方的自动翻唱。</small>}<JobProgress id={convertTask.id} onComplete={()=>void action(refresh)}/>
      <details><summary>自动翻唱与混音参数</summary><div className="toolbar"><label>人声增益 <input className="number" type="number" min="-40" max="12" value={vocalDb} onChange={e=>setVocalDb(Number(e.target.value))}/> dB</label><label>伴奏增益 <input className="number" type="number" min="-40" max="12" value={instDb} onChange={e=>setInstDb(Number(e.target.value))}/> dB</label><label><input type="checkbox" checked={includeBacking} onChange={e=>setIncludeBacking(e.target.checked)}/> 混入原和声</label><label>和声增益 <input className="number" type="number" min="-40" max="12" value={backingDb} onChange={e=>setBackingDb(Number(e.target.value))}/> dB</label><select aria-label="成品格式" value={format} onChange={e=>setFormat(e.target.value)}>{['wav','flac','mp3'].map(f=><option key={f}>{f}</option>)}</select></div></details><p>变调作用于转换人声，伴奏调性保持原样。自动翻唱保留分离出的伴奏和和声供下载与重新混音。</p><button className="primary" disabled={busy||coverTask.running||!model||!engines?.rvc.ready||selected?.metadata.kind!=='song'||!ready('vocals_melband_unwa')||!ready('lead_melband_aufr33')} onClick={()=>void action(async()=>{coverTask.track(await api<{id:string}>('/covers',json({source_id:audio,...parameters,segment_size:segment,overlap,profile,vocal_db:vocalDb,instrumental_db:instDb,backing_db:backingDb,include_backing:includeBacking,separate_backing:true,format})));})}>分离 → 转换 → 混音</button><JobProgress id={coverTask.id} onComplete={()=>void action(refresh)}/>
    </article>
    <article className="card"><h3>分离音轨与转换结果</h3>{items.filter(i=>i.exists&&((i.metadata.purpose==='conversion'&&i.metadata.kind==='separated_audio')||['converted_audio','mixed_audio'].includes(i.metadata.kind??''))).map(i=><div className="clip" key={i.id}><strong>{stemNames[i.metadata.stem??'']??i.name}</strong><small>{i.metadata.singer} / {i.name}</small><audio controls preload="none" src={`/api/artifacts/${i.id}/file`}/><a href={`/api/artifacts/${i.id}/file`} download>下载{stemNames[i.metadata.stem??'']??'音频'}</a></div>)}</article>
  </section>;
}
