import { useEffect,useState } from 'react';
import { api,json } from './api';
import { JobProgress,useTask } from './JobProgress';
interface Artifact {id:string;name:string;role:string;exists:boolean;metadata:{kind?:string;purpose?:string;stem?:string;singer?:string};}
export function MixPanel(){
  const [items,setItems]=useState<Artifact[]>([]),[vocal,setVocal]=useState(''),[inst,setInst]=useState(''),[backing,setBacking]=useState('');
  const [vocalDb,setVocalDb]=useState(0),[instDb,setInstDb]=useState(0),[backingDb,setBackingDb]=useState(0),[format,setFormat]=useState('wav');
  const [busy,setBusy]=useState(false),[error,setError]=useState('');const task=useTask('mix');
  const refresh=()=>api<{items:Artifact[]}>('/artifacts').then(d=>setItems(d.items));
  useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
  const audio=items.filter(i=>i.exists&&i.metadata.purpose!=='training'&&(i.role==='source'||['separated_audio','converted_audio'].includes(i.metadata.kind??'')));
  function options(){return audio.map(i=><option key={i.id} value={i.id}>{i.metadata.singer?`${i.metadata.singer} / `:''}{i.name}</option>);}
  return <section><div className="section-head"><div><h2>混音与导出</h2><p>重新组合转换人声、伴奏和可选和声，无需重新分离或变声。</p></div><button onClick={()=>void refresh().catch(e=>setError(e.message))}>刷新</button></div>{error&&<p className="error" role="alert">{error}</p>}<article className="card"><div className="toolbar"><label>人声 <select aria-label="混音人声" value={vocal} onChange={e=>setVocal(e.target.value)}><option value="">选择人声音轨</option>{options()}</select></label><label>伴奏 <select aria-label="混音伴奏" value={inst} onChange={e=>setInst(e.target.value)}><option value="">选择伴奏音轨</option>{options()}</select></label><label>和声 <select aria-label="混音和声" value={backing} onChange={e=>setBacking(e.target.value)}><option value="">不混入和声</option>{options()}</select></label></div><div className="toolbar"><label>人声音量 <input className="number" type="number" min="-40" max="12" value={vocalDb} onChange={e=>setVocalDb(Number(e.target.value))}/> dB</label><label>伴奏音量 <input className="number" type="number" min="-40" max="12" value={instDb} onChange={e=>setInstDb(Number(e.target.value))}/> dB</label><label>和声音量 <input className="number" type="number" min="-40" max="12" value={backingDb} onChange={e=>setBackingDb(Number(e.target.value))}/> dB</label><select value={format} onChange={e=>setFormat(e.target.value)} aria-label="导出格式">{['wav','flac','mp3'].map(f=><option key={f}>{f}</option>)}</select><button className="primary" disabled={busy||task.running||!vocal||!inst} onClick={()=>{setBusy(true);setError('');void api<{id:string}>('/mixing',json({vocal_id:vocal,instrumental_id:inst,backing_id:backing||null,vocal_db:vocalDb,instrumental_db:instDb,backing_db:backingDb,format})).then(task.track).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>混音导出</button></div><JobProgress id={task.id} onComplete={()=>void refresh().catch(e=>setError(e.message))}/><p>音轨时长差异超过 100 毫秒时会停止；必要时对整首统一衰减，避免削波。</p></article><article className="card"><h3>成曲</h3>{items.filter(i=>i.exists&&i.metadata.kind==='mixed_audio').map(i=><div className="clip" key={i.id}><strong>{i.name}</strong><audio controls preload="none" src={`/api/artifacts/${i.id}/file`}/><a href={`/api/artifacts/${i.id}/file`} download>下载成曲</a></div>)}</article></section>;
}
